### PR TITLE
Add support for interpolated docstrings

### PR DESCRIPTION
**Pull request by traviscrawford**
To simplify writing rule docstrings, and keeping common argument docstrings
consistent, here we add support for docstring interpolation. An example
use-case is a suite of rules (e.g.: foo_library, foo_binary, foo_test) that
all share some common arguments. Rather than copy/paste the argument
docstrings for each rule, adding support for string interpolation simplifies
writing docs and helps keep them in sync.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by traviscrawford** [comment]
I signed it!

**Comment by traviscrawford** [comment]
This issue came up while experimenting with generating docs for the Scala rules. In particular, there are a number of common args:

https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L510

This implementation is a sketch to run the idea by you. If you like this general concept I can add docs for this new convention, add a test, etc.

**Comment by davidzchen** [comment]
@traviscrawford - Sorry for the delay.

This is certainly an interesting idea. Do any of Python's docgen frameworks have a similar feature? Also, do you have an example of what the docstrings would look like with docstring interpolation?

**Pull request closed without merging**
