### PR TITLE
Add angle bracket escape to vm templates

### PR DESCRIPTION
**Pull request by blossommojekwu**

### CODE REVIEW

**Comment by c-parsons** [comment]
In the future, make sure your first commit contains a description of exactly what you're changing, so instead of "update func.vm" maybe "Add html angle bracket escaping for default templates"

Also, as we discussed offline, it looks like the rebuilt jars of this repository don't contain the java code which defines `util.htmlEscape`. Be sure to create a new pull request updating these jars first

Feel free to re-ping this PR when you're ready for me to take another look

**Comment by c-parsons** [comment]
Oof. As you can see by buildkite, this change breaks stardoc's self-documentation.

And in fact, it seems that html-escaping table cells seems to make it impossible to use formatting tags at all

FYI @brandjon  (isn't it great we can control escaping for each string? ;))

Maybe we update the default templates so that we don't do html escaping within tables.

**Comment by blossommojekwu** [comment]
PR is ready.

**Comment by brandjon** [comment]
> FYI @brandjon (isn't it great we can control escaping for each string? ;))

Agreed, but here's another concern. (This is nothing against your change, Blossom.)

If a template escapes in some situations but not others, that means that the .bzl author needs to know which parts of the docstring can have unescaped brackets, and which parts can take in HTML code. This is problematic because:

    1. It's surprising the first time you learn it, and hard to remember after you've learned it.

    2. It depends on the template used, and therefore doesn't encourage consistency between different .bzl authors and files. This makes it harder to adapt your knowledge to work on a different .bzl code base, and to compose .bzl dependencies with different conventions into a common project (though maybe you can say you wouldn't be running Stardoc on your dependencies).

```
def lt(x, y):
    """Returns <b>true</b> if  x < y.
    
    Args:
        x: the <b>first</b> number
        y: the <b>second</b> number
    """
    ...
```

It sounds like the current thinking is that (in the default template) the bold tags in the summary line would be escaped, but the ones in the Args lines would be emitted as formatting. Users will simply not remember that.

Ideally stardoc would present a common interface to all users regardless of the template. But this implies that stardoc has to take responsibility for evaluating formatting markup on its own, e.g. by doing some limited markdown parsing and creating an AST. Then we would escape all HTML content in HTML templates, because HTML would not be used for formatting purposes in the input, or if it were used, it would be up to Stardoc to parse it accordingly. The downside is that this requires stardoc to handle whatever use cases users currently have, like tables.

**Comment by c-parsons** [comment]
> (though maybe you can say you wouldn't be running Stardoc on your dependencies).

Indeed, I would. So we could consider taking the stance "you create your docstrings in whatever format you'd like, so long as you can generate documentation with them using stardoc (potentially given your custom input template)

That said, you bring up some good points. It may be unclean to have users write docstrings in vastly different ways. We don't currently take a stance on structured docstring "details" formatting. We may want to consider doing so going forward. For now, I think adhoc escaping with granular controls is "good enough".

**Comment by brandjon** [comment]
Hey, as a user, I was pretty pleased that the markdown-formatted docstrings I wrote months ago "just worked" when I added the Stardoc workflow to rules_python. So I don't mean to disagree about "good enough". ;)

**Comment by laurentlb** [comment]
I think it's useful to have consistency in the docstring format.
Stardoc is not the only tool looking at the docstrings, e.g. IDEs might want to parse the docstrings and present some information to the user.

**Comment by c-parsons** [comment]
Related: https://github.com/bazelbuild/skydoc/issues/183

I agree. Lets move any further discussion or proposals to that issue.

**Pull request merged**
