### PR TITLE
Use http_archive, not git_repository

### LINKED ISSUE #91: Use of git repository breaks old TLS implementation
On CircleCI, the ssh implementation doesn't support the newer TLS needed to make GitHub connections work. Therefore installing the skydoc repo causes an error:
```
ERROR: /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/external/io_bazel_skydoc/skylark/skylark.bzl:289:3: no such package '@gflags_repo//': Error cloning repository: ssh://git@github.com/google/python-gflags: Algorithm negotiation fail caused by ssh://git@github.com/google/python-gflags: Algorithm negotiation fail caused by Algorithm negotiation fail and referenced by '//external:gflags'
```
https://circleci.com/gh/bazelbuild/rules_nodejs/462

There is no good reason to ever clone a git repo in a repository rule, as we don't want all the commit history.

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #91

### CODE REVIEW

**Comment by jin** [comment]
Looks good, will merge after CI check

**Comment by jin** [comment]
Consider using [`new_http_archive.urls`](https://docs.bazel.build/versions/master/be/workspace.html#new_http_archive.urls) instead of `url`. `url` is deprecated in favor of `urls`.

**Comment by alexeagle** [comment]
Added another commit to fix all new_http_archive.url

**Comment by jin** [comment]
Thanks!

**Pull request merged**
