### PR TITLE
Add support for renaming output documentation files.

### PR DESCRIPTION
**Pull request by davidzchen**

### CODE REVIEW

**Comment by davidzchen** [comment]
+cc @garlicnation @kchodorow @damienmg

**Comment by garlicnation** [comment]
LGTM w/ the fix we discussed off-thread.

This should throw an error if renames are present but there is still a name conflict in the project.

**Comment by kchodorow** [comment]
LGTM.

**Comment by davidzchen** [comment]
Added validation for name conflicts. PTAL

**Comment by damienmg** [comment]
LGTM but I am a bit curious about what this feature will be used for.

**Comment by davidzchen** [comment]
The original use case for this is the fact that currently, the case where multiple `.bzl` files have the same basename is not handled very well, such as when we have `foo/bar/build_defs.bzl` and `foo/build_defs.bzl`.

One option I originally considered was to construct the same directory layout for the input files, which is the approach used by Javadoc and Rustdoc. For example, given the example above, the archive generated by Skydoc would contain:

```
output.zip
    foo/
        build_defs.md
        bar/
            build_defs.md
```

Based on an offline discussion with @garlicnation, this may not work very well internally. As a result, I implemented this solution, which is to support renaming output files. However, after thinking about it more, this approach will likely be confusing for many users.

Also, I found that [epydoc](http://epydoc.sourceforge.net/api/) does not re-create the directory structure of the source files but encodes the package paths in the output filenames. As a result, I decided to adopt this approach instead.

**Pull request closed without merging**
