### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dslomov**
Adding global CODEOWNERS

### CODE REVIEW

**Comment by aiuto** [comment]
Do we want this or https://github.com/bazelbuild/skydoc/pull/140
I had gone with sending /site to Serge.

**Comment by dslomov** [comment]
I am Ok with either version - @c-parsons please push either this PR or #140.

**Comment by dslomov** [comment]
friendly ping @c-parsons

**Comment by dslomov** [comment]
pinging @c-parsons @laurentlb :)

**Pull request merged**
